{
  nixpkgs-nixos-24-11-2025-03-24,
  bashHeader-2024-12-11,
  myPkgs-2024-12-11,
  nixos-system,
  ...
}:

let
  nixpkgs     = nixpkgs-nixos-24-11-2025-03-24;
  bashHeader  = bashHeader-2024-12-11;
  myPkgs      = myPkgs-2024-12-11;
in
  nixos-system
    {
      inherit nixpkgs bashHeader myPkgs;
      modules = { system, bash-header, my-pkgs, hpkgs, hlib }:
        [
          { nixpkgs.overlays =
              # to import each overlay individually
              # [ (import ../overlays/shntool.nix) ];

              # import everything from ../overlays/
              let
                lib = import ../lib.nix { plib = nixpkgs.lib; };
              in
                lib.importNixesNoArgs ../overlays;
          }
        ] ++
        (import ../hardware/lenovo-yoga-260.nix {
          inherit system bash-header hlib;
          hostname     = "dissolve";
          domainname   = "sixears.co.uk";
          # generated by `hex-addr red.sixears.co.uk`
          etherMac     = "fc:45:96:a9:a7:a6";
          wifiMac      = "Lenovo Yoga 260 Laptop Wireless";
          ip4addr      = "192.168.0.28";
          stateVersion = "22.05";

          systemPackages = pkgs: [
            (import ../pkgs/mkopenvpnconfs { inherit pkgs bash-header; })

            pkgs.shntool # see overlays/shntool.nix;
                         # picks up overlay for 24-bit WAV patch

            (import ../wifi-conns/bowery-secure-init.nix {inherit pkgs;})
          ];

          filesystems = [
            ../filesystems/std.nix
            ../filesystems/efi.nix
            ../filesystems/mobile-music.nix
            ../filesystems/local.nix
            # ../filesystems/local-nixpkgs.nix
            ../filesystems/usb-sdb.nix
          ];

          imports = pkgs: [
            # ../components/xserver-intel.nix
            ../components/greetd-sway.nix
            ../components/wayland.nix

            ../components/laptop.nix
            ../components/printing.nix
            ../components/deluge-killer.nix
            # this doesn't easily co-exist with home-backup.nix
            ../components/local-home-backup.nix

            (import ../components/desktop.nix { inherit pkgs my-pkgs; })
            ../components/scanning.nix
            ../openvpn/no-autostart.nix
            ../components/nix-serve.nix
            ../dns-server/cloudflare.nix
#            ../components/zsa.nix

            ../components/finbar.nix
            ../components/keyboardio.nix

            ../components/cgroup-users.nix

            ../users/people/martyn.nix
            ../users/people/xander.nix
            ../users/people/syncthing-martyn.nix
          ];
        });
    }
