{ nixpkgs, nixos-system }:

nixos-system {
  modules = { system, bash-header, hpkgs }:
    [
      { nixpkgs.overlays =
          # to import each overlay individually
          # [ (import ../overlays/shntool.nix) ];

          # import everything from ../overlays/
          let
            lib = import ../lib.nix { plib = nixpkgs.lib; };
          in
            lib.importNixesNoArgs ../overlays;
      }
    ] ++
    (import ../hardware/dell-xps-13-9310.nix {
      inherit system bash-header;
      hostname     = "red";
      domainname   = "sixears.co.uk";
      logicalCores = 12;
      # generated by `hex-addr red.sixears.co.uk`
      etherMac     = "72:65:64:2e:73:69";
      wifiMac      = "Dell XPS 9315 Laptop Wireless";
      stateVersion = "22.05";
      systemPackages = pkgs: [
        (import ../pkgs/mkopenvpnconfs { inherit pkgs bash-header; })
        (import ../pkgs/wifi.nix { inherit pkgs; })

        pkgs.shntool # see overlays/shntool.nix;
                     # picks up overlay for 24-bit WAV patch

        (import ../wifi-conns/bowery-secure-init.nix {inherit pkgs;})

        (hpkgs.acct)
      ];
      filesystems = [
        ../filesystems/efi.nix
        ../filesystems/mobile-music.nix
        ../filesystems/local.nix
        ../filesystems/usb-sda.nix
      ];
      imports = pkgs: [
        (import ../xserver.nix { inherit pkgs bash-header; })
        ../xserver-dvorak.nix
        ../xserver-intel.nix

        ../laptop.nix
        ../printing.nix
        ../deluge-killer.nix
        # this doesn't easily co-exist with home-backup.nix
        ../local-home-backup.nix

        ../desktop.nix
        ../pulseaudio.nix
        ../scanning.nix
        ../openvpn.nix
        ../nix-serve.nix
        ../dns-server/cloudflare.nix

        ../finbar.nix
        ../keyboardio.nix

        ../users/people/martyn.nix
        ../users/people/syncthing-martyn.nix
      ];
    });
}
